stop_words = [",", ".", "...", ":", "\"", "(", ")", "Brian", "BRIAN", "BDG", "Pat", "Patrick", "Clayton", "uh", "Uh", "um", "Um", 
"so", "So", "SO", "you", "You", "YOU", "a", "an", "A", "AN", "hell", "HELL", "also", "ALSO", "just", "Just", "JUST", "also", "Also", 
"ALSO", "maybe", "Maybe", "MAYBE", "dunno", "Dunno", "DUNNO", "neat", "Neat", "NEAT", "cool", "Cool", "COOL", "on", "off", "over",
"under", "again", "further", "ah", "Ah", "Ah",
# following are the nltk stop words
'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 
'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 
'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 
'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 
'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 
'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 
'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 
'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 
'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', 
"couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 
'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', 
"weren't", 'won', "won't", 'wouldn', "wouldn't", 'ON', 'OFF', 'OVER', 'UNDER', 'AGAIN', 'FURTHER', 'I', 'ME', 'MY', 'MYSELF', 'WE', 
'OUR', 'OURS', 'OURSELVES', 'YOU', "YOU'RE", "YOU'VE", "YOU'LL", "YOU'D", 'YOUR', 'YOURS', 'YOURSELF', 'YOURSELVES', 'HE', 'HIM',
'HIS', 'HIMSELF', 'SHE', "SHE'S", 'HER', 'HERS', 'HERSELF', 'IT', "IT'S", 'ITS', 'ITSELF', 'THEY', 'THEM', 'THEIR', 'THEIRS', 
'THEMSELVES', 'WHAT', 'WHICH', 'WHO', 'WHOM', 'THIS', 'THAT', "THAT'LL", 'THESE', 'THOSE', 'AM', 'IS', 'ARE', 'WAS', 'WERE', 
'BE', 'BEEN', 'BEING', 'HAVE', 'HAS', 'HAD', 'HAVING', 'DO', 'DOES', 'DID', 'DOING', 'A', 'AN', 'THE', 'AND', 'BUT', 'IF', 'OR',
'BECAUSE', 'AS', 'UNTIL', 'WHILE', 'OF', 'AT', 'BY', 'FOR', 'WITH', 'ABOUT', 'AGAINST', 'BETWEEN', 'INTO', 'THROUGH', 'DURING',
'BEFORE', 'AFTER', 'ABOVE', 'BELOW', 'TO', 'FROM', 'UP', 'DOWN', 'IN', 'OUT', 'ON', 'OFF', 'OVER', 'UNDER', 'AGAIN', 'FURTHER', 
'THEN', 'ONCE', 'HERE', 'THERE', 'WHEN', 'WHERE', 'WHY', 'HOW', 'ALL', 'ANY', 'BOTH', 'EACH', 'FEW', 'MORE', 'MOST', 'OTHER', 
'SOME', 'SUCH', 'NO', 'NOR', 'NOT', 'ONLY', 'OWN', 'SAME', 'SO', 'THAN', 'TOO', 'VERY', 'S', 'T', 'CAN', 'WILL', 'JUST', 'DON', 
"DON'T", 'SHOULD', "SHOULD'VE", 'NOW', 'D', 'LL', 'M', 'O', 'RE', 'VE', 'Y', 'AIN', 'AREN', "AREN'T", 'COULDN', "COULDN'T", 'DIDN',
"DIDN'T", 'DOESN', "DOESN'T", 'HADN', "HADN'T", 'HASN', "HASN'T", 'HAVEN', "HAVEN'T", 'ISN', "ISN'T", 'MA', 'MIGHTN', "MIGHTN'T", 
'MUSTN', "MUSTN'T", 'NEEDN', "NEEDN'T", 'SHAN', "SHAN'T", 'SHOULDN', "SHOULDN'T", 'WASN', "WASN'T", 'WEREN', "WEREN'T", 'WON', 
"WON'T", 'WOULDN', "WOULDN'T",  'On', 'Off', 'Over', 'Under', 'Again', 'Further', 'Ah', 'Ah', 'Ah', 'I', 'Me', 'My', 'Myself', 
'We', 'Our', 'Ours', 'Ourselves', 'You', "You'Re", "You'Ve", "You'Ll", "You'D", 'Your', 'Yours', 'Yourself', 'Yourselves', 
'He', 'Him', 'His', 'Himself', 'She', "She'S", 'Her', 'Hers', 'Herself', 'It', "It'S", 'Its', 'Itself', 'They', 'Them', 'Their', 
'Theirs', 'Themselves', 'What', 'Which', 'Who', 'Whom', 'This', 'That', "That'Ll", 'These', 'Those', 'Am', 'Is', 'Are', 'Was', 
'Were', 'Be', 'Been', 'Being', 'Have', 'Has', 'Had', 'Having', 'Do', 'Does', 'Did', 'Doing', 'A', 'An', 'The', 'And', 'But', 'If',
'Or', 'Because', 'As', 'Until', 'While', 'Of', 'At', 'By', 'For', 'With', 'About', 'Against', 'Between', 'Into', 'Through', 
'During', 'Before', 'After', 'Above', 'Below', 'To', 'From', 'Up', 'Down', 'In', 'Out', 'On', 'Off', 'Over', 'Under', 'Again', 
'Further', 'Then', 'Once', 'Here', 'There', 'When', 'Where', 'Why', 'How', 'All', 'Any', 'Both', 'Each', 'Few', 'More', 'Most',
'Other', 'Some', 'Such', 'No', 'Nor', 'Not', 'Only', 'Own', 'Same', 'So', 'Than', 'Too', 'Very', 'S', 'T', 'Can', 'Will', 
'Just', 'Don', "Don'T", 'Should', "Should'Ve", 'Now', 'D', 'Ll', 'M', 'O', 'Re', 'Ve', 'Y', 'Ain', 'Aren', "Aren'T", 'Couldn', 
"Couldn'T", 'Didn', "Didn'T", 'Doesn', "Doesn'T", 'Hadn', "Hadn'T", 'Hasn', "Hasn'T", 'Haven', "Haven'T", 'Isn', "Isn'T", 'Ma',
'Mightn', "Mightn'T", 'Mustn', "Mustn'T", 'Needn', "Needn'T", 'Shan', "Shan'T", 'Shouldn', "Shouldn'T", 'Wasn', "Wasn'T", 'Weren',
"Weren'T", 'Won', "Won'T", 'Wouldn', "Wouldn'T", 'On', 'Off', 'Over', 'Under', 'Again', 'Further', 'I', 'Me', 'My', 'Myself', 
'We', 'Our', 'Ours', 'Ourselves', 'You', "You'Re", "You'Ve", "You'Ll", "You'D", 'Your', 'Yours', 'Yourself', 'Yourselves', 'He', 
'Him', 'His', 'Himself', 'She', "She'S", 'Her', 'Hers', 'Herself', 'It', "It'S", 'Its', 'Itself', 'They', 'Them', 'Their', 
'Theirs', 'Themselves', 'What', 'Which', 'Who', 'Whom', 'This', 'That', "That'Ll", 'These', 'Those', 'Am', 'Is', 'Are', 'Was',
'Were', 'Be', 'Been', 'Being', 'Have', 'Has', 'Had', 'Having', 'Do', 'Does', 'Did', 'Doing', 'A', 'An', 'The', 'And', 'But', 
'If', 'Or', 'Because', 'As', 'Until', 'While', 'Of', 'At', 'By', 'For', 'With', 'About', 'Against', 'Between', 'Into', 'Through',
'During', 'Before', 'After', 'Above', 'Below', 'To', 'From', 'Up', 'Down', 'In', 'Out', 'On', 'Off', 'Over', 'Under', 'Again',
'Further', 'Then', 'Once', 'Here', 'There', 'When', 'Where', 'Why', 'How', 'All', 'Any', 'Both', 'Each', 'Few', 'More', 'Most',
'Other', 'Some', 'Such', 'No', 'Nor', 'Not', 'Only', 'Own', 'Same', 'So', 'Than', 'Too', 'Very', 'S', 'T', 'Can', 'Will', 
'Just', 'Don', "Don'T", 'Should', "Should'Ve", 'Now', 'D', 'Ll', 'M', 'O', 'Re', 'Ve', 'Y', 'Ain', 'Aren', "Aren'T", 'Couldn',
"Couldn'T", 'Didn', "Didn'T", 'Doesn', "Doesn'T", 'Hadn', "Hadn'T", 'Hasn', "Hasn'T", 'Haven', "Haven'T", 'Isn', "Isn'T", 
'Ma', 'Mightn', "Mightn'T", 'Mustn', "Mustn'T", 'Needn', "Needn'T", 'Shan', "Shan'T", 'Shouldn', "Shouldn'T", 'Wasn', 
"Wasn'T", 'Weren', "Weren'T", 'Won', "Won'T", 'Wouldn', "Wouldn'T"]
