stop_words = [",", ".", "...", ":", "\"", "(", ")", "Brian", "BRIAN", "BDG", "Pat", "Patrick", "Clayton", "uh", "Uh", "um", "Um", 
"so", "So", "SO", "you", "You", "YOU", "hell", "HELL", "also", "ALSO", "just", "Just", "JUST", "also", "Also", 
"ALSO", "neat", "Neat", "NEAT", "cool", "Cool", "COOL", "on", "off", "over",
"under", "again", "further", "ah", "Ah", "Ah",
# following are the nltk stop words
'our', 'ours', 'ourselves', "you're", "you've", "you'll", "you'd", 'yours', 
'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 
'they', 'them', 'their', 'theirs', 'themselves',  'this', 'that', "that'll", 'these', 'those', 'am', 'the', 
'as', 'at',  'for', 'with', 'about', 'against', 'between', 'into', 
'through', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 
'again', 'further', 'then', 'once', 'here', 'there', 'other', 'some', 'such',  'nor', 'own', 'same', 'so', 'than', 'too', 'very', 
'now', 
'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't",  'ma', 
'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren',
'OUR', 'OURS', 'OURSELVES', "YOU'RE", "YOU'VE", "YOU'LL", "YOU'D", 'YOURS', 'YOURSELF', 'YOURSELVES', 'HE', 'HIM', 'HIS', 'HIMSELF',
'SHE', "SHE'S", 'HER', 'HERS', 'HERSELF', 'IT', "IT'S", 'ITS', 'ITSELF', 'THEY', 'THEM', 'THEIR', 'THEIRS', 'THEMSELVES', 'THIS',
'THAT', "THAT'LL", 'THESE', 'THOSE', 'AM', 'THE', 'AS', 'AT',  'FOR', 'WITH', 'ABOUT', 'AGAINST', 'BETWEEN', 'INTO', 'THROUGH',
'ABOVE', 'BELOW', 'TO', 'FROM', 'UP', 'DOWN', 'IN', 'OUT', 'ON', 'OFF', 'OVER', 'UNDER', 'AGAIN', 'FURTHER', 'THEN', 'ONCE', 
'HERE', 'THERE', 'OTHER', 'SOME', 'SUCH', 'NOR', 'OWN', 'SAME', 'SO', 'THAN', 'TOO', 'VERY', 'NOW', 'HADN', "HADN'T", 'HASN', 
"HASN'T", 'HAVEN', "HAVEN'T", 'MA', 'MIGHTN', "MIGHTN'T", 'MUSTN', "MUSTN'T", 'NEEDN', "NEEDN'T", 'SHAN', "SHAN'T", 'SHOULDN', 
"SHOULDN'T", 'WASN', "WASN'T", 'WEREN', 'Our', 'Ours', 'Ourselves', "You'Re", "You'Ve", "You'Ll", "You'D", 'Yours', 'Yourself', 
'Yourselves', 'He', 'Him', 'His', 'Himself', 'She', "She'S", 'Her', 'Hers', 'Herself', 'It', "It'S", 'Its', 'Itself', 'They', 'Them',
'Their', 'Theirs', 'Themselves', 'This', 'That', "That'Ll", 'These', 'Those', 'Am', 'The', 'As', 'At',  'For', 'With', 
'About', 'Against', 'Between', 'Into', 'Through', 'Above', 'Below', 'To', 'From', 'Up', 'Down', 'In', 'Out', 'On', 'Off', 'Over', 
'Under', 'Again', 'Further', 'Then', 'Once', 'Here', 'There', 'Other', 'Some', 'Such', 'Nor', 'Own', 'Same', 'So', 'Than', 'Too', 
'Very', 'Now', 'Hadn', "Hadn'T", 'Hasn', "Hasn'T", 'Haven', "Haven'T", 'Ma', 'Mightn', "Mightn'T", 'Mustn', "Mustn'T", 'Needn',
"Needn'T", 'Shan', "Shan'T", 'Shouldn', "Shouldn'T", 'Wasn', "Wasn'T", 'Weren']

x = [word.title() for word in stop_words]
print(x)